const EXTENSION_MAP = {
  js: "javascript",
  jsx: "jsx",
  ts: "typescript",
  tsx: "tsx",
  py: "python",
  rb: "ruby",
  rs: "rust",
  go: "go",
  java: "java",
  kt: "kotlin",
  swift: "swift",
  c: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  h: "c",
  hpp: "cpp",
  cs: "csharp",
  php: "php",
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  sass: "sass",
  less: "less",
  json: "json",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  xml: "xml",
  svg: "xml",
  md: "markdown",
  mdx: "mdx",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  fish: "bash",
  ps1: "powershell",
  sql: "sql",
  graphql: "graphql",
  gql: "graphql",
  dockerfile: "dockerfile",
  tf: "hcl",
  hcl: "hcl",
  vue: "vue",
  svelte: "svelte",
  astro: "astro",
  lua: "lua",
  r: "r",
  scala: "scala",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  clj: "clojure",
  dart: "dart",
  groovy: "groovy",
  gradle: "groovy",
  pl: "perl",
  pm: "perl",
  hs: "haskell",
  elm: "elm",
  nim: "nim",
  zig: "zig",
  proto: "protobuf",
  prisma: "prisma",
  env: "bash",
  ini: "ini",
  cfg: "ini",
  conf: "nginx",
  nginx: "nginx",
  lock: "yaml",
  txt: "text",
  log: "text",
};

const FILENAME_MAP = {
  dockerfile: "dockerfile",
  "docker-compose.yml": "yaml",
  "docker-compose.yaml": "yaml",
  makefile: "makefile",
  rakefile: "ruby",
  gemfile: "ruby",
  "gemfile.lock": "text",
  podfile: "ruby",
  ".gitignore": "bash",
  ".gitattributes": "text",
  ".editorconfig": "ini",
  ".eslintrc": "json",
  ".prettierrc": "json",
  ".babelrc": "json",
  ".nvmrc": "text",
  ".node-version": "text",
  ".env": "bash",
  ".env.local": "bash",
  ".env.example": "bash",
  "package.json": "json",
  "package-lock.json": "json",
  "yarn.lock": "text",
  "pnpm-lock.yaml": "yaml",
  "tsconfig.json": "json",
  "jsconfig.json": "json",
  "vite.config.js": "javascript",
  "vite.config.ts": "typescript",
  "webpack.config.js": "javascript",
  "rollup.config.js": "javascript",
  "tailwind.config.js": "javascript",
  "postcss.config.js": "javascript",
  "jest.config.js": "javascript",
  "vitest.config.js": "javascript",
  readme: "markdown",
  "readme.md": "markdown",
  changelog: "markdown",
  "changelog.md": "markdown",
  license: "text",
  "license.md": "markdown",
};

const LANGUAGE_DISPLAY_NAMES = {
  javascript: "JavaScript",
  jsx: "JSX",
  typescript: "TypeScript",
  tsx: "TSX",
  python: "Python",
  ruby: "Ruby",
  rust: "Rust",
  go: "Go",
  java: "Java",
  kotlin: "Kotlin",
  swift: "Swift",
  c: "C",
  cpp: "C++",
  csharp: "C#",
  php: "PHP",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  sass: "Sass",
  less: "Less",
  json: "JSON",
  yaml: "YAML",
  toml: "TOML",
  xml: "XML",
  markdown: "Markdown",
  mdx: "MDX",
  bash: "Bash",
  powershell: "PowerShell",
  sql: "SQL",
  graphql: "GraphQL",
  dockerfile: "Dockerfile",
  hcl: "HCL",
  vue: "Vue",
  svelte: "Svelte",
  astro: "Astro",
  lua: "Lua",
  r: "R",
  scala: "Scala",
  elixir: "Elixir",
  erlang: "Erlang",
  clojure: "Clojure",
  dart: "Dart",
  groovy: "Groovy",
  perl: "Perl",
  haskell: "Haskell",
  elm: "Elm",
  nim: "Nim",
  zig: "Zig",
  protobuf: "Protocol Buffers",
  prisma: "Prisma",
  ini: "INI",
  nginx: "Nginx",
  makefile: "Makefile",
  text: "Plain Text",
};

const LANGUAGE_COLORS = {
  javascript: "#f1e05a",
  typescript: "#3178c6",
  jsx: "#f1e05a",
  tsx: "#3178c6",
  python: "#3572A5",
  ruby: "#701516",
  rust: "#dea584",
  go: "#00ADD8",
  java: "#b07219",
  kotlin: "#A97BFF",
  swift: "#F05138",
  c: "#555555",
  cpp: "#f34b7d",
  csharp: "#178600",
  php: "#4F5D95",
  html: "#e34c26",
  css: "#563d7c",
  scss: "#c6538c",
  vue: "#41b883",
  svelte: "#ff3e00",
  dart: "#00B4AB",
  scala: "#c22d40",
  elixir: "#6e4a7e",
  haskell: "#5e5086",
  lua: "#000080",
  r: "#198CE7",
  shell: "#89e051",
  bash: "#89e051",
  powershell: "#012456",
  sql: "#e38c00",
  graphql: "#e10098",
  dockerfile: "#384d54",
  markdown: "#083fa1",
};

const getFileLanguage = (filename) => {
  if (!filename) return "text";

  const lowerName = filename.toLowerCase();

  if (FILENAME_MAP[lowerName]) {
    return FILENAME_MAP[lowerName];
  }

  const lastDotIndex = lowerName.lastIndexOf(".");
  if (lastDotIndex === -1) {
    return FILENAME_MAP[lowerName] || "text";
  }

  const extension = lowerName.slice(lastDotIndex + 1);
  return EXTENSION_MAP[extension] || "text";
};

const getLanguageDisplayName = (language) => {
  if (!language) return "Text";
  return LANGUAGE_DISPLAY_NAMES[language] || language;
};

const getLanguageColor = (language) => {
  if (!language) return "#8b949e";
  return LANGUAGE_COLORS[language.toLowerCase()] || "#8b949e";
};

const getFileIcon = (filename, type = "file") => {
  if (type === "dir") return "folder";

  const language = getFileLanguage(filename);

  const iconMap = {
    javascript: "file-code",
    typescript: "file-code",
    jsx: "file-code",
    tsx: "file-code",
    python: "file-code",
    ruby: "file-code",
    rust: "file-code",
    go: "file-code",
    java: "file-code",
    html: "file-code",
    css: "file-code",
    json: "file-json",
    yaml: "file-code",
    markdown: "file-text",
    text: "file-text",
    bash: "terminal",
    dockerfile: "box",
    sql: "database",
    graphql: "share-2",
  };

  return iconMap[language] || "file";
};

export {
  getFileLanguage,
  getLanguageDisplayName,
  getLanguageColor,
  getFileIcon,
  LANGUAGE_COLORS,
  LANGUAGE_DISPLAY_NAMES,
};
